### ISSUE TITLE
Installation schon möglich

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.vis-2-widgets-weather#14]
Hallo,

kann man schon testen?

Habe via Url installiert, bleibt bei der Installation aber hängen.

FG
Sigi

Plattform: Windows
Betriebssystem: win32
Architektur: x64
Modell: Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
RAM: 15.9 GB
Node.js: v20.13.1
NPM: 10.5.2
Admin: 6.17.14
JS: 5.0.19

**Comment by rg-engineering** [comment]
eigentlich sollte man testen können. Ich habe bisher immer per tarball installiert, das hat funktioniert. Versuche gerade über URL, da hängt das System... Muss ich mir anschauen...

**Comment by rg-engineering** [comment]
Installation funktioniert schon, dauert aber:


```
user@nanopi-r4s:~$ iobroker url https://github.com/rg-engineering/ioBroker.vis-2-widgets-weather
install rg-engineering/ioBroker.vis-2-widgets-weather#b7d4e1b84db0db6a9059bfa770bd7d3d910fc5a2
NPM version: 10.5.0
Installing rg-engineering/ioBroker.vis-2-widgets-weather#b7d4e1b84db0db6a9059bfa770bd7d3d910fc5a2... (System call)

changed 2 packages in 14m

178 packages are looking for funding
  run `npm fund` for details
upload [0] vis-2-widgets-weather.admin /opt/iobroker/node_modules/iobroker.vis-2-widgets-weather/admin/vis-2-widgets-weather.png vis-2-widgets-weather.png image/png
Adapter "system.adapter.vis-2.0" restarted.


```

**Comment by sigi2345** [comment]
Jupp, hat eine Weile gedauert.
Leider sind die Widgets unter Vis2 nicht vorhanden.Instanz hinzugefügt und Upload gemacht.

**Comment by sigi2345** [comment]
Keine Chance die Widgets irgendwie unter Windows zu installieren.

**Comment by rg-engineering** [comment]
Unter iobroker\iobroker-data\files\vis-2\widgets\vis-2-widgets-weather fehlt wahrscheinlich die customWidgets.js ?

**Comment by sigi2345** [comment]
> Unter iobroker\iobroker-data\files\vis-2\widgets\vis-2-widgets-weather fehlt wahrscheinlich die customWidgets.js ?

Da fehlt der Ganze Ordner

![Screenshot (802)](https://github.com/rg-engineering/ioBroker.vis-2-widgets-weather/assets/41079106/032139aa-b8d1-4a1a-a108-726165d35196)

**Comment by sigi2345** [comment]
Ordner jetzt da aber es fehlt jetzt tatsächlich die customWidgets.js

**Comment by rg-engineering** [comment]
Ich kann das Problem nun hier nachvollziehen, suche die Ursache...

**Comment by rg-engineering** [comment]
Bei mir hat es jetzt mit folgendem Ablauf funktioniert:
* benutzerdefinerte Installation aus https://github.com/rg-engineering/ioBroker.vis-2-widgets-weather
* danach eine Instanz anlegen
* und dann noch vis-2 ("Visualisierung Next Generation") upload ausführen

Das hat dann das Verzeichnis und auch das js-File angelegt...

**Comment by sigi2345** [comment]
> Bei mir hat es jetzt mit folgendem Ablauf funktioniert:
> 
> * benutzerdefinerte Installation aus https://github.com/rg-engineering/ioBroker.vis-2-widgets-weather
> * danach eine Instanz anlegen
> * und dann noch vis-2 ("Visualisierung Next Generation") upload ausführen
> 
> Das hat dann das Verzeichnis und auch das js-File angelegt...

Hat bei mir nicht funktioniert.
Welche VIS-2 Version hast du?

**Comment by rg-engineering** [comment]
habe auch die v2.9.64, die Fehler im log scheinen aber vis-2 Fehler zu sein...

**Comment by sigi2345** [comment]
> habe auch die v2.9.64, die Fehler im log scheinen aber vis-2 Fehler zu sein...
> 
> @GermanBluefox any ideas on that?

Nach wie das selbe Problem mit Version 0.3.2 (2024-06-30)

**Comment by GermanBluefox** [comment]
Ich konnte installiert. Dauert aber.

**Comment by rg-engineering** [comment]
@sigi2345 hilft das?

**Comment by sigi2345** [comment]
> @sigi2345 hilft das?

Ja, Super bis auf die Icons.


![Screenshot (873)](https://github.com/user-attachments/assets/889bc049-91aa-4a40-b4ea-d4b6ded67202)

**Comment by rg-engineering** [comment]
ja, das mit den Icons habe ich schon gesehen.
Wäre gut, für alles, was auffällt, ein issue hier aufzumachen. Ich habe noch so viele todo's hier, als issue geht es wenigstens nicht verloren. Vielen Dank.

**Comment by sigi2345** [comment]
Ok, erledigt.
